version: '3.8'

name: keygate

services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/keygate-api
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=keygate
      - MYSQL_USER=keygate-api
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: