import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, UserButton, currentUser } from "@clerk/nextjs";
import Sidebar from "../components/Sidebar";
import { ConfigProvider, Layout } from "antd";
import { Content } from "antd/es/layout/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ConfigProvider
        theme={{
          token: {
            fontFamily: "Inter, sans-serif",
          },
          components: {
            Table: {
              fontSize: 12,
            },
          },
        }}
      >
        <html lang="en">
          <body className={inter.className}>
            <div className="flex flex-row w-full p-0 m-0">
              <Layout>
                <Sidebar />
                <Content className="flex-grow bg-gradient-to-b from-[#F9FAFA] to-[#EBF0F1]">
                  {children}
                </Content>
              </Layout>
            </div>
          </body>
        </html>
      </ConfigProvider>
    </ClerkProvider>
  );
}
